### ISSUE TITLE
Can't find any browser that will print properly

### ISSUE THREAD

**Issue by pdf** [mephitrpg/rpg-cards#40] opened 2015-09-08 00:44 UTC
- Chrome (multiple versions) does this:
  ![rpg-cards1](https://cloud.githubusercontent.com/assets/146192/9724169/69c42ca2-5616-11e5-93db-c334dc1991c4.png)
- Firefox (multiple versions) prints only the first page.
- IE11 crashes when asked to print.
- ~~I tried reducing the page height for Chrome until it fit on a page, but the backs are offset by 2-3mm both horizontally and vertically.~~

**Comment by pdf** [comment] 2015-09-08 06:36
Turns out the last point is a bug with the duplexer in my printer, and #41 fixes the chrome page break problem, so I'm now able to print cards successfully using manual duplexing, thanks!

**Comment by dchapes** [comment] 2015-09-17 14:14
FYI, Firefox 40.0.3 on FreeBSD also only prints the first page for me. I've tried all the print options I could and couldn't get that to change.

Edit: looking at closed issues I found this: https://github.com/crobi/rpg-cards/issues/18#issuecomment-64954884
Which suggests select-all (Ctrl-A) then using "print selection", although that produces multiple pages they are completely uselessly misaligned. I understand if this is a Firefox issue that is considered not worth working around (if even possible to work around) but perhaps it warrants a warning/comment in the print help that multiple pages may not work with Firefox.

**Comment by lucidobservor** [comment] 2015-09-17 14:30
I'm not sure if this is the same problem or merely a related one, since it
has an intervening step. I'm on what I assume is the latest version of
Chrome. For printing, I print from Chrome and select the "save as  pdf"
option, then take that pdf to a FedEx print shop. The pdf looks fine, but
when I try to print the pdf there, it only prints the first page and then
stops. As a workaround, running their scan cleanup on the document causes
it to print mostly correctly, but they occasionally charge extra for that
service.

Does that sound familiar to anyone? If anyone else has successfully printed
from a FedEx shop, how did you manage it?

**Comment by crobi** [comment] 2015-09-17 21:26
It looks indeed as there is a regression with the printing. I have merged #41 for a quick fix.

Automatically positioning items on print pages is a pain in CSS. In retrospect, I think it would have been better to use absolute positions.

**Comment by Enekk** [comment] 2015-12-04 01:23
Even after the #41, I am unable to properly print in Chrome.  Even with margins set to 'none' in the save as PDF, I get cards which display across pages.  I also get pages of nothing but grey.
See: ![screenshot from 2015-12-03 20-21-37](https://cloud.githubusercontent.com/assets/1928133/11579389/a8ff9d1a-99fb-11e5-9c2b-39d96ed2a29c.png)

**Comment by crobi** [comment] 2015-12-04 10:12
I forgot to update the online preview after the merge of #41. I fixed this now. Can you try again? If it still does not work, make sure your browser does not use an old cached version (e.g., clear the browser cache).

The way I implemented how cards are placed on a page is really brittle. The next version of rpg-cards should rethink this from the ground up.

> I also get pages of nothing but grey.

There is a forced page break after each block of cards. If such a block spreads only a little into the next page, the remainder of that page will be empty (gray). Making the block of cards exactly as large as one sheet of paper (for double-sided printing alignment) but not larger is what doesn't work robustly right now.

**Comment by Enekk** [comment] 2015-12-04 11:34
I can confirm that I am now able to correctly save the cards!  Thanks!

**Closed as completed** 2015-12-31 08:46 UTC
