### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by manemeth** [mephitrpg/rpg-cards#62] opened 2016-06-27 15:06 UTC
Perhaps this is just me, but I can't seem to get these to print with the images/formatting. 

I've tried two different machines, three different browsers.  Everything disappears but the text and the boarders.

**Comment by crobi** [comment] 2016-06-27 17:06
Almost certainly a duplicate of #17. 

Feel free to reopen this issue if enabling the printing background images did not solve your issue.

**Closed as completed by crobi** 2016-06-27 17:06 UTC
Labels: duplicate
