### ISSUE TITLE
Icon updates

### ISSUE THREAD

**Issue by jasonmiceli** [mephitrpg/rpg-cards#47] opened 2016-01-26 01:19 UTC
Hi all - non-engineer here. I simply want to offer a major THANK YOU to the team behind this, and a +1 for any way the icon updating can be automated, so simpleton folk like I can more readily use the tool with the latest icons available. 

Thanks, and cheers!

**Comment by crobi** [comment] 2016-01-30 07:07
Duplicate of #39

**Closed as completed by crobi** 2016-01-30 07:07 UTC
