### ISSUE TITLE
Export as JPG file

### ISSUE THREAD

**Issue by Riotpopper** [mephitrpg/rpg-cards#48] opened 2016-01-30 00:14 UTC
This program is great, everything looks spiffy and it's super easy to use!
My only suggested enhancement would be a way to export everything as an image file instead of just a printable section, I just don't know how that would be done, sadly.

**Comment by crobi** [comment] 2016-01-30 07:06
Duplicate of #27?

**Closed as not planned** 2022-11-23 00:01 UTC
Labels: enhancement, wontfix
